CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50)
);



INSERT INTO COMPANY (ID, NAME, AGE,ADDRESS) VALUES (1, 'soumya', 28,'Surathkal,Karnataka');

UPDATE COMPANY SET AGE = 29 WHERE ID=1;

SELECT * from COMPANY;

DELETE FROM COMPANY WHERE ID=1;
